### ISSUE TITLE
Some effects lacking a "continue" mode.

### ISSUE THREAD

**Issue by zorggn** [steffest/BassoonTracker#1]
Effects 3, 4, 7, 9 should use the last values given to them in a channel, if they show up in a pattern with 00 as parameter; testing showed that at least the Set Offset effect currently doesn't do this.

signia.mod (3rd & 4th channels, pattern 3 in 3rd order) - 900 doesn't retain the first value of 0x14.

**Comment by steffest** [comment]
True!
Some trackers also continue the effect this way for effect 1 and 2 , but protracker does not.
BTW: signia.mod also uses the pattern delay effect which is not yet implemented - that's next.
