### ISSUE TITLE
XM Bugs - Arpeggio

### ISSUE THREAD

**Issue by steffest** [steffest/BassoonTracker#11]
Split from #8 

Some have issues with arpeggios:

maniac-disco zax.xm
carter-dead feelings.xm
med-halloween 2002.xm (seems that a 'note-off' technique isn't working here)
lhs-brd keygen #2.mod and brd keygen #2.xm both don't work properly!

**Comment by steffest** [comment]
Should be all fixed now.
Those mod files that are converted XM files I'm going to ignore.
For example lhs-brd2.mod not only goes out of range in the arpeggio, but also uses notes that are outside the .mod scope. (displayed as ??? in protracker)
I don't want to stuff the tracker with options to cater for every little quirk in every browser. There will always be little differences in playback routines so I'll settle for "normal" protracker and fasttracker playback compatibility.

**Comment by bryc** [comment]
Nice work! Those XM files work nicely now.

The ??? notes originate in FastTracker 1.0 from 1992 along with the 8xx and E8x panning commands. FastTracker 2 supports saving .MOD in the same way. I understand not supporting features that only work in one tracker, etc. In fact ProTracker 3.x doesn't even play some MODs made in PT1 or PT2 properly! It is all a headache. 

But your XM player is in itself a MOD player that supports these extended features. A user can simply switch to XM mode at any time if he/she wants to play those problematic MOD files! The only issue is, the ??? notes are stripped away from the pattern data so the XM mode cannot access it.

Perhaps make the MOD player simply ignore those notes outside range, but keep the data there for XM mode?
