### ISSUE TITLE
XM bug: solo on channel 9 also solos channel 1

### ISSUE THREAD

**Issue by JamesDunne** [steffest/BassoonTracker#18]
Reproduction steps:
1. Load Ambrozia XM demo song
3. Browse to sequence 06 (pattern 05)
2. Click [S] button on channel 9 to solo

Expected:
Only channel 9 should be audible.

Actual:
Both channel 9 and channel 1 are audible.

Notes:
No other channel solo function seems to exhibit this bug, at least on this demo song.

**Comment by steffest** [comment]
True, it depends on the current cursor pos.
Confirmed as UI bug.
