### ISSUE TITLE
http://www.stef.be/bassoontracker/docs/trackerQuircks.txt missing

### ISSUE THREAD

**Issue by speeder** [steffest/BassoonTracker#19]
So, I really, really wanted to read that file... it sounds rather amusing and interesting to learn the technical parts of it..

but the link is broken, and the file seemly is not on the repository at all...

:(

**Comment by steffest** [comment]
Found it!
There are lot's more little thingies - some of them I don't understand well enough to write them down.
Sagamusix of OpenMPT has a nice list of them.
