### ISSUE TITLE
Bassoon tracker to friendUp Os. 

### ISSUE THREAD

**Issue by Sheeva007** [steffest/BassoonTracker#3]
@steffest Can you make a port under FriendOS a os on the cloud. 
https://friendsoftware.cloud/developers/friendup-open-source/

Have look . Bassoon tracker can come come THE masterpiece.

Thx. Dominique.

**Comment by steffest** [comment]
Although FriendUP seems a very interesting project, implementing bassoontracker on top of it is outside the scope at this moment. I'll keep it in mind.

**Comment by steffest** [comment]
I'm going to shelf this again - I got an integration working (parked at http://www.stef.be/bassoontracker/friendUp/ ) of the FileSystem and the Friend Menu but the platform seem to go through some (breaking) changes currently - maybe later.

**Comment by steffest** [comment]
And opened again :-)
Most of it is down now.
It's integrated in the main source.
Friend Specific Code is in the hosts/FriendOS folder.
You can build the Friend version by executing "grunt friend" in the root of the project.
Still need to figure out how to build a decent installable Friend Package, though ...

**Comment by steffest** [comment]
Done - still needs some improvements (Drag/Drop - mime types, ...) but the build for FriendOS is now part of the main build process.
