### ISSUE TITLE
GUI: Knob doesn't take effect when turned on without adjusting

### ISSUE THREAD

**Issue by BleuLlama** [steffest/BassoonTracker#36]
This one was hard to summarize for the title. ;)

If you start up playback the tracker, the first time you turn on an EQ adjustment in the FX panel of a voice, it will not apply the knob's setting until you adjust it a little.  

reproducing this:

1. Reload the page
2. Load and play a mod (I was using "go cryo go" by U4IA )
3. Select one of the voices, preferably one with a high-hat (third voice for this mod)
4. Select FX
5. click on the "HIGH" eq adjustment, but do not drag.  The light on the knob will light up
6. Audio is unaffected.
7. drag to adjust the knob, and it will pop up to a higher level. 

Adjusting it back to the center position has more "brightness" than when it was off.

**Comment by steffest** [comment]
Confirmed - I'm still not really sure how to integrate these FX knobs into the tracker concept.
You can't set their values like you can with other effects and obviously the MOD or XM fileformat has no support for them. 
Future will tell but in the end a specific "bassoon" fileformat seems inevitable.
