### ISSUE TITLE
Command Speed "F00" should be ignored

### ISSUE THREAD

**Issue by mnemo70** [steffest/BassoonTracker#44]
The file "[dirt.mod](http://modland.com/pub/modules/Protracker/Nightlight/dirt.mod)" has F00 commands in the song at which point Bassoon Tracker stops playback. Other players (OpenMPT, FLOD) seem to ignore setting the speed to zero, which seems okay to me.

**Comment by steffest** [comment]
Hmm .. that's one of those things that is handled differently in different trackers.
In both Protracker 2.3 and FasttrackerII the F00 command stops playback.
I'll think about it but for now I think I'll keep it this way.
Thanks for checking!
