### ISSUE TITLE
feature: Add Midi keyboard support 

### ISSUE THREAD

**Issue by blurymind** [steffest/BassoonTracker#47]
Testing my keystation 32 mini here:
http://www.multiplayerpiano.com
and
https://pianu.com/intro/ode-to-joy

Works. All the keys are detected and so is their pressure sensitivity.

Trying the same here
https://www.stef.be/bassoontracker/

My midi keyboard simply doesn't exist to bassoon tracker. Pressing all the keys on various instruments - nothing.

Can you add support for midi keyboards please? I will help with testing if need be. Using a standard laptop laptop keyboard is just  subpar when compared to using a midi keyboard with pressure sensitivity

Not sure exactly how some of these web apps get their midi support. I assume they use some open source js library to achieve it
https://github.com/djipco/webmidi
or see many others here
https://www.npmjs.com/search?q=midi%20keyboard

this one is popular and well maintained
https://www.npmjs.com/package/jzz
also works! test here
https://jazz-soft.net/demo/SelectMidi.html

Midi keyboards are pretty cheap these days - especially on ebay. Having one greatly enhances the experience of music making with a tracker. To me a tracker without support for midi keyboards is not complete - it is crippled. Thus why I really need this feature before I can use bassoon

**Comment by steffest** [comment]
Yes, that's on the road map (see first items of "Future plans" in the readme.)
Although I play some piano myself and have 2 midi keyboards, the tracker concept - with it's numerical effect entering and non-graphical editing - is tailor-made for computer keyboards. Therefor a computer keyboard will always be the main input method. 
That being said: Don't worry: midi keyboard support will be added as it's obviously a more musical and natural input method for the more experienced musician.

**Comment by blurymind** [comment]
Is there anything I can do to help?  Have you picked what library to use?
Looking at the code it seems keyboard input is set in
https://github.com/steffest/BassoonTracker/blob/master/script/src/ui/input.js
so I assume that the midi will be added there too?

**Comment by blurymind** [comment]
The midi input would make a huge difference, as it will give us button pressure :D

**Comment by blurymind** [comment]
it looks like we dont need a library to do this. There is already a web api for it
https://codepen.io/Rumyra/pen/NxdbzL

**Comment by steffest** [comment]
Midi-in is supported now

**Comment by blurymind** [comment]
Thank you for adding this feature.It makes a huge difference in how we can use bassoon! :tada: :musical_keyboard:

**Comment by blurymind** [comment]
One thing I wound add to this - can we make midi input to be enabled by default? Some people might be too lazy to look for it in the settings and just assume its not supported
