### ISSUE TITLE
Player API

### ISSUE THREAD

**Issue by FreeTalent-BB** [steffest/BassoonTracker#53]
I preloading all my musics in an array of songs. How to change the current song of player, without to reload each music file?

And I to load a music from an ArrayBuffer ?

Possible to have the unminified JS of BassonTracker Player?

Thanks

**Comment by steffest** [comment]
Hey!
Sure, you can check out the source files of the player as defined in https://github.com/steffest/BassoonTracker/blob/master/Gruntfile.js#L43

But to get you going I've put an unminified version on 
http://www.stef.be/bassoontracker/player/src/

And yes: You can load a file from an arraybuffer with the Tracker.processFile function:
https://github.com/steffest/BassoonTracker/blob/master/script/src/tracker.js#L1906

This takes an ArrayBuffer as first parameter and the filename as second.
(And optionally a callback function as third when process the file is done)

Let me know If you need any more info.
Cheers!
