### ISSUE TITLE
Sound triggered by input doesnt play during play+record mode

### ISSUE THREAD

**Issue by blurymind** [steffest/BassoonTracker#6]
First of all - WOW! This is the most feature complete html5 tracker I have ever seen. I love the retro vibes to it too!

The biggest problem with it for me atm is the fact that sound triggered by keyboard keys during play+record mode does not play at all. The recorded notes play on the replay of the loop though.

Is this something that you plan to address or it is a genuine bug? It really makes the tracker unusable for live record mode for me

**Comment by steffest** [comment]
Good point ... it's a bit my design but I must say I never use play+record myself :-) 
I always "construct" the song in record mode without playing because I find the play+record thing not precise enough for my clumsy fingers.
I'll fix it in the next version.

**Comment by blurymind** [comment]
Thank you @steffest 😄 
Yes I understand this way of working by construct. I used to do it too, but then I bought a cool little
keystation midi keyboard. It's quite fun to explore melodies in real time record mode. Then once I have  recorded something, then fix the clumsy notes by editing them.
I am quite clumsy too you see, but I love recording live more and then fixing errors. It's hard for me to come up with tunes via construction alone.

I guess everyone has a way.  Thank you for addressing this. I love your tracker btw. You managed to capture a lot of nostalgia in it too

**Comment by steffest** [comment]
Fixed now - preview of the dev version is on https://www.stef.be/bassoontracker/dev.html 
Your next question probably will be to make the insert en backspace keys work as intented so that you can quickly shift notes up or down :-)
This will be fixed soon too.

**Comment by blurymind** [comment]
@steffest that was quick! Thank you 😄 
I will try it after work.  Btw you anticipated it very well. Shifting notes with these two keys would be quite nice to have and also easier than cut and pasting - so thank you for also looking into that
