### ISSUE TITLE
option to save the track sample as Wav file - request

### ISSUE THREAD

**Issue by alexgoldblat** [steffest/BassoonTracker#65]
Hi first of all amazing JS application!!  love is very much!
wonder if there is option to save the sample of the track from the Sample edit view .

**Comment by steffest** [comment]
Yes there is.
If you hit the "File" button and then "Save" -> "Sample" you can save the current sample.
![image](https://user-images.githubusercontent.com/763047/109668262-4a1f0580-7b71-11eb-95f8-cfe244f9767d.png)

If you mean 'the entire track as sample" you can first render the current pattern to an empty sample slot using the menu "Edit => Render Pattern 2 Sample"
