### ISSUE TITLE
Cannot locate spritesheet v4 and spritesmap v4 on latest release

### ISSUE THREAD

**Issue by DeStilleGast** [steffest/BassoonTracker#71]
![image](https://user-images.githubusercontent.com/3677706/128208201-ade66dc0-b179-4dab-9a08-9a4fb3c0d120.png)

I tried to download from release tab or even from the git clone, but doesn't seem to be here, tried to rename v3 to v4 but that did not do the trick as it dumps a other error

**Comment by DrSnuggles** [comment]
Quick solution is to grab file from here:
https://www.stef.be/bassoontracker/skin/spritesheet_v4.png?v=0.3.10-build20210216.0229

**Comment by steffest** [comment]
Whoops, forgot to include them - fixed now in https://github.com/steffest/BassoonTracker/commit/63faaa1e3506eb1a76d1716bf736f02ca565a12c
