### ISSUE TITLE
loading samples

### ISSUE THREAD

**Issue by ayskura** [steffest/BassoonTracker#75]
loading samples hide the instrument section, therefore to load few samples you need to load on sample, change view to change instrument, then load another sample etc... making the process very long and tedious... also not many audio format are recognised, such as FLAC, it would be great to have them working

**Comment by steffest** [comment]
You can also change instruments from the sample editor so a faster flow would be => Open the "load sample" screen and the "sample edit screen", load your sample, change the sample number (next to the sample name input in the sample editor), load sample, ....

If you have your sample locally on your filesystem you can also drag/drop them on the tracker to load them.

All Audio formats supported by webAudio are supported - including FLAC - but you are right that the file extention was not recognised, that's fixed now so loading FLAC samples should work.
