### ISSUE TITLE
Issues related to debranu.mod by Solaris

### ISSUE THREAD

**Issue by RocketeerEatingEggs** [steffest/BassoonTracker#80]
debranu.mod by Solaris (https://modarchive.org/index.php?request=view_by_moduleid&query=194194) is mis-identified as an 8SVX file if you load it directly from your computer. It is also stuck at the loading phase if you load it from https://www.stef.be/bassoontracker/?file=https%3A%2F%2Fapi.modarchive.org%2Fdownloads.php%3Fmoduleid%3D194194
According to OpenMPT, the file was saved with ProTracker 3.61, while normal 4-channel MODs (e.g. some of the demo MODs) report as having been made with "Generic ProTracker or compatible", which implies that this may be a slightly different format from regular ProTracker.

**Comment by steffest** [comment]
Indeed - that file is in the IFF MODL format that was proposed/used in Protracker 3.01 beta and onwards.
During the mid 90's, numerous different file format proposals were launched but none made it into "mainstream". 
There are currently no plans to support these as it's too much of a niche.

**Comment by steffest** [comment]
(That being said - I will filter those out in the internal database so you won't stumble upon them by accident while loading mods directly from within BassoonTracker)
