### ISSUE TITLE
Feature: keyboard change sample (up/down)

### ISSUE THREAD

**Issue by tofu13** [steffest/BassoonTracker#82]
Nice to have a pair of keys to change the current sample up/down.

**Comment by steffest** [comment]
Right! 
Will add it.

**Comment by steffest** [comment]
Keyboard Shortcuts added: +/- to select sample up/down (both on num keypad as regular keyboard) 
Num keypad 0-9 to direct select sample 1-10.
-> https://www.stef.be/bassoontracker/docs/#keyboard_commands
