### ISSUE TITLE
Should the app run in the browser locally?

### ISSUE THREAD

**Issue by Buy-One** [steffest/BassoonTracker#83]
The online version works for me in Chrome 94.0.4606.61 (x64), but the same version does not run offline in the same browser.

Some calls fail in all 3 HTML files. A call to analytics.js fails in the online version as well but not the rest.

![image](https://user-images.githubusercontent.com/61803004/229376968-071be4c5-d5da-406a-b7e3-afb866448913.png)

**Comment by steffest** [comment]
It does, but you have to serve it from a "webserver", not open the index.html file directly from the filesystem in your browser.
There a nice list of options on https://medium.com/swlh/need-a-local-static-server-here-are-several-options-bbbe77e59a11

The last one might be handy: a chrome extension that let you quickly setup a local webserver:
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en

**Comment by Buy-One** [comment]
Thank you
