### ISSUE TITLE
Does not seem to work offline for me

### ISSUE THREAD

**Issue by starvixen64** [steffest/BassoonTracker#85]
Downloading the master as a .zip, opening either dev.html or index.html causes both Firefox and Edge to get stuck on a black screen that says "Loading...".

Unsure why this happens, but I also get these messages in console.

```
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page. audio.js:83:18
initialising main.js:7:17
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///D:/WebApps/BassoonTracker-master/skin/spritemap_v4.json?v=1682469170232&r=1682469170414. (Reason: CORS request not http).
```

This is by far the nicest looking web-based tracker I've found, so what could be causing this hang?

**Comment by steffest** [comment]
Hey!
As BassoonTracker is a web-application, you can't just open the index.html in your browser, you need to "serve it from a webserver".
You can do this locally on your machine and even offline.
A good list of options is e.g. https://medium.com/swlh/need-a-local-static-server-here-are-several-options-bbbe77e59a11

Another one I can recommend is "Spark" -> https://github.com/rif/spark/releases
Download the binary for your platform, drop the Spark executable in the folder where you extracted the BassoonTracker files and run it.
If you then point your browser to http://localhost:8080/ it should work.

**Comment by DrSnuggles** [comment]
At least in Google Chrome you can install it as a PWA (ProgressiveWebApp) and use it offline.
https://www.stef.be/bassoontracker/
There is an "install" symbol in the address bar. 
After installation you will find a shortcut on your desktop.

**Comment by starvixen64** [comment]
> Hey! As BassoonTracker is a web-application, you can't just open the index.html in your browser, you need to "serve it from a webserver". You can do this locally on your machine and even offline. A good list of options is e.g. https://medium.com/swlh/need-a-local-static-server-here-are-several-options-bbbe77e59a11
> 
> Another one I can recommend is "Spark" -> https://github.com/rif/spark/releases Download the binary for your platform, drop the Spark executable in the folder where you extracted the BassoonTracker files and run it. If you then point your browser to http://localhost:8080/ it should work.

Thanks, I'm not too familiar with web apps that work like this so wasn't aware :)

> At least in Google Chrome you can install it as a PWA (ProgressiveWebApp) and use it offline. https://www.stef.be/bassoontracker/ There is an "install" symbol in the address bar. After installation you will find a shortcut on your desktop.

Unfortunately Firefox removed installing PWAs on desktop (seems to work on mobile though), so I'll have to use that spark solution or something similar
