### ISSUE TITLE
No clear indicator if a file was not found/failed to load

### ISSUE THREAD

**Issue by DeStilleGast** [steffest/BassoonTracker#86]
Basicly what the titles says, I noticed that a sample/demo song in bassoon was taking ages to load.
after inspection I found out that the file did not exist on my local server, 

trying to load as example: "62-channels: forever young xm", the loading indicator shows and stays there until you load a file that does exist but in the console you can see that the server returned a 404 but gets overshadowed by a wall from a exception that tells me that variable a is undefined

![image of my console](https://github.com/steffest/BassoonTracker/assets/3677706/066cd9b2-0009-4e3d-9a0c-7879a7d46338)

**Comment by steffest** [comment]
Indeed!
The UI now shows an error message in these cases:
<img width="144" alt="image" src="https://github.com/user-attachments/assets/fc0fef43-b6d4-4c9a-9a20-8d29519daf15">
